components/LoginForm.js
components/RegisterForm.js
models/User.js
pages/api/auth/login.js
pages/api/auth/register.js
pages/login.js
pages/register.js
utils/auth.js

added all required files to handling login/registration

Merge task#2 to development

---

components/Dashboard.js
components/LoginForm.js
components/RegisterForm.js
components/styles/Dashboard.css
components/styles/LoginForm.css
components/styles/RegisterForm.css
pages/dashboard.js

Added dashboard with some login and register style change

Added dashboard

---

.github/workflows/codeql-analysis.yml
.github/workflows/continuous-integration.yml

- Add 2 workflows to run on PRs and main branch to support CI/CD deployment

Add starting setup

---

chathaven/.eslintrc.json
chathaven/package-lock.json
chathaven/package.json
chathaven/src/components/Dashboard.js
chathaven/src/pages/api/auth/me.js
chathaven/src/pages/api/auth/register.js

Implemented admin registration and updated dashboard to allow only admins to create teams.
If you register as an admin it will be true in mongodb and false otherwise. 
If you login only as a user, you wont be able to see the create teams button.

Registration as admin and only admins can create teams

---

chathaven/src/components/CMsWindow.js
chathaven/src/components/Dashboard.js
chathaven/src/models/Channel.js
chathaven/src/pages/api/channelsmessages.js

Feature works now with logging in and out tested also

In channel messaging

---

chathaven/src/components/Dashboard.js

deleted pesky div

---

chathaven/src/components/CMsWindow.js
chathaven/src/components/Dashboard.js
chathaven/src/components/styles/Dashboard.css
chathaven/src/pages/api/channelsmessages.js
chathaven/src/pages/api/users.js

Feature to set the message box on the right side based on who sent a message, added names to messages

Other channel messaging features

---

chathaven/src/components/Dashboard.js
chathaven/src/models/User.js
chathaven/src/pages/api/channels.js
chathaven/src/pages/api/teams.js
chathaven/src/pages/api/user.js

Added functionality for admins to be able to see/interact with and in all teams and channels.
<br/>
> [!CAUTION]
- To see the deployment visit [chathaven.onrender.com](https://chathaven.onrender.com)

Implemented global admin to be able to see and enter every team and channel

---

chathaven/src/components/Dashboard.js

Added function created by Lucas that was not pushed weirdly
<br/>
> [!CAUTION]
- To see the deployment visit [chathaven.onrender.com](https://chathaven.onrender.com)

Created missing method

---

.github/pull_request_template.md
chathaven/src/app/page.tsx
chathaven/src/components/DMsDashboard.js
chathaven/src/components/Dashboard.js
chathaven/src/components/Home.js
chathaven/src/pages/api/auth/login.js
chathaven/src/pages/api/auth/me.js
chathaven/src/pages/api/auth/register.js
chathaven/src/pages/api/channels.js
chathaven/src/pages/api/channelsmessages.js
chathaven/src/pages/api/dms.js
chathaven/src/pages/api/dmsmessages.js
chathaven/src/pages/api/teams.js
chathaven/src/pages/api/user.js
chathaven/src/pages/api/users.js
chathaven/src/pages/dashboard.js
chathaven/src/pages/dms.js
chathaven/src/pages/login.js
chathaven/src/pages/register.js

Replace this with the changes in this PR
<br/>
> [!CAUTION]
- To see the deployment visit [chathaven.onrender.com](https://chathaven.onrender.com)

Fix imports

---

.github/pull_request_template.md
chathaven/src/app/page.tsx
chathaven/src/components/DMsDashboard.js
chathaven/src/components/Dashboard.js
chathaven/src/components/Home.js
chathaven/src/pages/api/auth/login.js
chathaven/src/pages/api/auth/me.js
chathaven/src/pages/api/auth/register.js
chathaven/src/pages/api/channels.js
chathaven/src/pages/api/channelsmessages.js
chathaven/src/pages/api/dms.js
chathaven/src/pages/api/dmsmessages.js
chathaven/src/pages/api/teams.js
chathaven/src/pages/api/user.js
chathaven/src/pages/api/users.js
chathaven/src/pages/dashboard.js
chathaven/src/pages/dms.js
chathaven/src/pages/login.js
chathaven/src/pages/register.js

3rd test deployment

---

chathaven/package-lock.json
chathaven/package.json

Fix tailwind

---

chathaven/package-lock.json
chathaven/package.json

Fix dependancies

---

chathaven/package-lock.json
chathaven/package.json

5th test deployment

---

chathaven/package.json
chathaven/tsconfig.json

Temporarily disable lint

---

chathaven/tsconfig.json

another attempt

---

chathaven/next.config.ts
chathaven/package-lock.json

Return development to normal config

---

chathaven/package-lock.json
chathaven/src/components/CreateDMMenu.js
chathaven/src/components/DMsDashboard.js
chathaven/src/components/Dashboard.js

Fix lint warnings

---

chathaven/src/components/styles/DMs.css
chathaven/src/components/styles/Dashboard.css

fixed DM and Teams list covered by logout

---

chathaven/src/components/AddUserToChannelMenu.js
chathaven/src/components/CMsWindow.js
chathaven/src/components/CreateChannelMenu.js
chathaven/src/components/Dashboard.js
chathaven/src/components/styles/Dashboard.css
chathaven/src/models/User.js
chathaven/src/pages/api/available-users.js
chathaven/src/pages/api/channels.js
chathaven/src/pages/api/user.js

Added functionality for admins to add users to existing channels. Also added functionality for users that create channels to become admins of that channel.
> [!CAUTION]

User adding to existing channel and User becoming channel admin when create

---

.github/pull_request_template.md
chathaven/src/components/RegisterForm.js
chathaven/src/pages/api/auth/register.js

- Add invisible field to catch bots
- Update pull request template
> [!CAUTION]

Deployment protection

---

chathaven/src/components/LoginForm.js
chathaven/src/components/RegisterForm.js
chathaven/src/components/styles/LoginForm.css
chathaven/src/components/styles/RegisterForm.css

- fixed frontend of error messages when registering/logging in
> [!CAUTION]

UI fix for error messages in login/register

---

chathaven/src/components/DMsDashboard.js
chathaven/src/components/Dashboard.js
chathaven/src/components/LogoutButton.js
chathaven/src/components/styles/DMs.css
chathaven/src/components/styles/Dashboard.css

- Changed placement of logout button area to be vertically to the left of the team sidebar
> [!CAUTION]

Changed logout button area placement

---

chathaven/postcss.config.mjs
chathaven/tailwind.config.js

Add back tailwind content section

---

.github/workflows/continuous-integration.yml
chathaven/package-lock.json
chathaven/package.json
chathaven/server.js
chathaven/src/components/Dashboard.js
chathaven/src/components/LogoutButton.js
chathaven/src/components/SocketClient.js
chathaven/src/components/SocketContext.js
chathaven/src/components/styles/Dashboard.css
chathaven/src/components/styles/SocketClient.css
chathaven/src/models/LastActiveTime.js
chathaven/src/pages/api/lastactivetime.js
chathaven/src/pages/dashboard.js

- Installed Express, Socket.io, and Socket.io-client using the command `npm install express socket.io socket.io-client`.
- Added a server.js file in the root directory of chathaven which initializes a socket server. The file server.js is ran independently and simultaneously with the frontend using the command `node server.js`. 
- Added a mouse and keyboard tracker inside the Dashboard for updating status to away.
- Moved the handling of the logout button to the Dashboard as the SocketProvider did not encompass that component.
> [!CAUTION]

Implement the user status & presence feature

---

chathaven/src/components/Dashboard.js
chathaven/src/components/EditProfileMenu.js
chathaven/src/components/SocketClient.js
chathaven/src/components/styles/SocketClient.css

Enhanced the user status UI 

---

chathaven/next.config.mjs
chathaven/package-lock.json
chathaven/package.json
chathaven/src/components/CMsWindow.js
chathaven/src/components/styles/Dashboard.css

- quick fix for css file
> [!CAUTION]

forgot to save css file, pushing to dev

---

.github/workflows/codeql-analysis.yml
.github/workflows/continuous-integration.yml
chathaven/__tests__/components/RequestToJoinChannelMenu.test.js

Unit tests sprints 3 and 4

---

chathaven/src/components/CMsWindow.js
chathaven/src/components/CreateDMMenu.js
chathaven/src/components/DMsWindow.js
chathaven/src/components/styles/DMs.css
chathaven/src/components/styles/Dashboard.css
chathaven/src/models/DMs.js
chathaven/src/pages/api/dmsmessages.js

added camera and reactions to the DMs dashboard
> [!CAUTION]

Frontend fixes

---

chathaven/package-lock.json
chathaven/src/components/CMsWindow.js
chathaven/src/components/DMsDashboard.js
chathaven/src/components/DMsWindow.js
chathaven/src/components/styles/DMs.css
chathaven/src/components/styles/Dashboard.css
chathaven/src/models/Channel.js
chathaven/src/models/DMs.js
chathaven/src/pages/api/channelsmessages.js
chathaven/src/pages/api/dmsmessages.js

- Changed the schema of messages for both DMs and Channels to include a tag field
- Tags are fetched when discussions are loaded and appended to database when messages are sent
- Frontend also allows user to create a new tag of their own (custom tag)
> [!CAUTION]

Implement a feature that allows users to add tags onto their messages in both DMs and in channels in the Dashboard

---

chathaven/__tests__/components/DMsWindow.test.js
chathaven/src/components/DMsWindow.js
chathaven/src/components/MessageBubble.js
chathaven/src/components/styles/DMs.css
chathaven/src/models/DMs.js
chathaven/src/pages/api/dmsmessages.js

- vanish mode feature where users can send a message in vanish mode, and then the message will dissapear after the other user has read the message
> [!CAUTION]

Vanish messages logic implemented

---

chathaven/src/components/DMsDashboard.js

- Added a function to handle the logout from the dms page and added the router to move to the login page when intended.
> [!CAUTION]

Changed the logic for handling logout from dms and add comments

---

chathaven/src/components/AlertPopup.js
chathaven/src/components/CMsWindow.js
chathaven/src/components/DMsDashboard.js
chathaven/src/components/DMsWindow.js
chathaven/src/components/Dashboard.js
chathaven/src/components/SocketContext.js
chathaven/src/components/styles/AlertPopup.css

- Added the tooltip of the status button 
- Allowed user to move mouse and type on keyboard while unavailable
> [!CAUTION]

Added the tooltip of the status button and allowed user to move mouse while unavailable

---

chathaven/src/components/AlertPopup.js
chathaven/src/components/CMsWindow.js
chathaven/src/components/DMsDashboard.js
chathaven/src/components/DMsWindow.js
chathaven/src/components/styles/AlertPopup.css

- When tags are selected the menu automatically closes and an alert displaying the chosen tag appears.
> [!CAUTION]

Added alerts when tags are selected and additional comments
